### PR TITLE
Step 2 UI with tests. Closes #12.

### LINKED ISSUE #12: Data load Step 2
dataloader_02

### PR DESCRIPTION
**Pull request by gvidon**
## Short recap
- Sample of user data on top of the page
- forms for editing fields properties
- restrictions on concepts
- navigating between steps
- tested
- restructured tests dir a little bit.
## Details
- Tests are ok https://travis-ci.org/openspending/os-import
- html/css are quite simple
- columns forms area width is limited by CSS to demonstrate horizontal scrolling.

Deployed this branch to heroku http://os-import.herokuapp.com/

### CODE REVIEW

**Comment by pwalsh** [comment]
@gvidon 

I've done a code review now. I'm going to list some specific things related to the feature here, and open a separate issue for issues of design and architecture.
- If I go straight to the route for step 2 `/map` I get some errors in the console, and I'm not directed instead to step one (ie: there is no management of the user flow)
- If I enter data and then reload the page, I lose everything I added (there is no local persistence of data entered - this is really important in a multi-step user flow)
- Step 2 changes are not persisted at all (even without a reload as above) - I can change "description", "data type", and "concept" for any field, then move back to step 1, and then move back again to step 2, and my changes are gone
- Probably related to above, when I look at the data package object in the console, the mapping object is empty, even when I have added concepts etc. in the UI (see screenshot below)
- There is no validation on user actions on both the "data type" and "concept" selectors. For example:
  - I can easily set a column that has a string like "Australia" in it to be data type integer
  - I can easily set a column that has a string like "Australia" in it to be concept Date/Time
- The mock UI described in the issue for step 2 shows data and the controls in a delineated table that is left aligned, and there is some vertical and horizontal consistency. The task here was not to implement "design", but still, what is implemented is very hard to read as things do not line up horizontally, there are no lines to delineate cells, etc.
- Likewise, the mock UI in the issue has a clear separator with he word "description". This makes it easy to distinguish between the data and the controls - please do implement the same
- The UI has a horizontal scroll for the data/controls layout even when it does not need one (3 columns)
- The issue asks for "Unit tests for discrete logic (eg: updating mapping etc)", in addition to functional tests. As far as I see, all tests use zombie to perform functional tests via the UI layer, but I am really looking to see how the core logic is tested without the UI layer. The ability to unit test logic helps me see that there is clear separation between the view layer and the logic layer of the app.

no_persistent_mapping

**Comment by gvidon** [comment]
@pwalsh 
- I didn't work on persistent state of user data after page reload, though I agree it should be helpful. Data just passed from one step to another. I would like to move it into distinct task, to keep tasks smaller. And should be it done before we implement auth in this app?
- html is just for example, I put no efforts on it, as I thought it will be seriously refined later. Will adjust rows height.
- there are couple tests cases which test methods of mapping views — https://github.com/openspending/os-import/blob/feature/step-2-manually-correct/tests/mapper.js#L119. They are written with zombie, as there are some problems running backbone views with backbone-base extension outside browser environment. We will have much more unit tests after I move data package methods into model during this tasks https://github.com/openspending/os-import/issues/27

**Comment by gvidon** [comment]
@pwalsh so, regarding to what I have written above I would just fix html, move persistent state into another task and proceed with #27.

After data package methods are incapsulated into single point and tested I would move into fixes of Step 1 and Step 2.

**Comment by pwalsh** [comment]
@gvidon 

I made two points above about state:
- reload page
- back and forth between step 1 and step 2

I can accept that reload page is a different task, as it requires using local storage, but the other point is really a bug (see my other point about nothing being put into the `mapping` property of the DP) in this implementation and I'm not moving it to a different task.

Likewise, with the unit tests: we have a real problem if we can't test logic without a browser! I've made various notes about this at #30 . Any extension we use that forces such patterns on the code should be avoided.

**Comment by gvidon** [comment]
Short recap with TODO
- [x] Show message when user opens `/map` directly
- [x] do not reset Step 2 when user comes back to Step 1, changes nothing and then returns to Step 2
- [ ] validate concept to correspond to column data type
- [x] arrange form rows/labels height
- [x] remove columns list width limitation
- [ ] tests

**Comment by gvidon** [comment]
> - There is no validation on user actions on both the "data type" and "concept" selectors. For example:
>   - I can easily set a column that has a string like "Australia" in it to be data type integer

@pwalsh does that mean that we have to disallow user changing column types? Or what's the rule/algorithm on possible options in column types selector?

In my opinion restricting options in column types selectors will require type prediction, which is already done in jts-infer. Probably the good idea would be to allow user select column type if only jts-infer didn't have good enough prediction.

So, from what I learned we should just
- allow only String/Date/Time/Datetime columns as Date / Time concept
- allow only integer columns as Amount concept

**Comment by pwalsh** [comment]
@gvidon remember, the infer method is based on those type-casting functions. It should be easy to take a sample value for each time the user changes, and just cast that value.

**Comment by gvidon** [comment]
@pwalsh yes, I know that infer method does type casting. Do you mean that it can return set of possible types for each column? And we should let user change column type if only infer didn't cast single type?

**Pull request closed without merging**
